title: BHP
email: benjamin@hamblinpyke.net
description: Benjamin Hamblin-Pyke's homepage
baseurl:
url: https://www.hamblinpyke.net
locale: en-gb
twitter_username: hamblin-pyke



# Build settings
markdown: kramdown
theme: jekyll-swiss
plugins:
  - jekyll-json-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - deploy.sh
